train:
  windows:
    datasets_path: "../datasets_local"
    batch_size: 8
    workers: 4
    cache: false
  linux:
    datasets_path: "../datasets"
    batch_size: 24
    workers: 10
    cache: true

  model_name:
    - "yolo11n_C2PSA_DIFF_C3k2FDConv.yaml"
    - "yolo11n_C2PSA_DIFF_DEConv.yaml"
    - "yolo11n_C2PSA_DIFF_DEConv1.yaml"
    - "yolo11n_C3k2DEConv1.yaml"
    - "yolo11n_C3k2DEConv_C3k2WTConv.yaml"
    - "yolo11n_C3k2WTConv_C3k2FDConv.yaml"

  dataset_yaml: "/NWPU_VHR.yaml"
  epochs: 300
  close_mosaic: 45
  seed: 42
  optimizer: "SGD"
  amp: false
  patience: 0
  pretrained: true
  module_edition: "e0"