train:
  windows:
    datasets_path: "../datasets_local"
    batch_size: 8
    workers: 4
    cache: false
  linux:
    datasets_path: "../datasets"
    batch_size: 24
    workers: 10
    cache: true

  model_name:
    - "yolo11n_C3k2DFF1.yaml"
    - "yolo11n_C3k2DFF2.yaml"
    - "yolo11n_C3k2Dual.yaml"
    - "yolo11n_C3k2HetConv1.yaml"
    - "yolo11n_C3k2HetConv2.yaml"
    - "yolo11n_C3k2iAFF.yaml"
    - "yolo11n_C3k2MSCB1.yaml"
    - "yolo11n_C3k2MSCB2.yaml"
    - "yolo11n_C3k2ODConv.yaml"
    - "yolo11n_C3k2PConv1.yaml"
    - "yolo11n_C3k2PConv2.yaml"
    - "yolo11n_LAE.yaml"
    - "yolo11n_ODConv.yaml"

  dataset_yaml: "/NWPU_VHR.yaml"
  epochs: 300
  close_mosaic: 45
  seed: 42
  optimizer: "SGD"
  amp: false
  patience: 0
  pretrained: true
  module_edition: "e0"