train:
  windows:
    datasets_path: "../datasets_local"
    batch_size: 8
    workers: 4
    cache: false
  linux:
    datasets_path: "../datasets"
    batch_size: 24
    workers: 10
    cache: true

  model_name:
    - "yolo11n_C3k2CGHalfConv.yaml"
    - "yolo11n_C3k2DEConv.yaml"
    - "yolo11n_C3k2FasterPConv.yaml"
    - "yolo11n_C3k2FDConv.yaml"
    - "yolo11n_C3k2GBConv.yaml"
    - "yolo11n_C3k2GhostDynamicConv.yaml"
    - "yolo11n_C3k2GSConv.yaml"
    - "yolo11n_C3k2ID.yaml"
    - "yolo11n_C3k2IDINB.yaml"
    - "yolo11n_C3k2LDConv.yaml"
    - "yolo11n_C3k2MKP.yaml"
    - "yolo11n_C3k2MRFAConv.yaml"
    - "yolo11n_C3k2MSGD1.yaml"
    - "yolo11n_C3k2MSGD2.yaml"
    - "yolo11n_C3k2OREPA1.yaml"
    - "yolo11n_C3k2OREPA2.yaml"
    - "yolo11n_C3k2OREPA3.yaml"
    - "yolo11n_C3k2PSConv.yaml"
    - "yolo11n_C3k2RFAConv.yaml"
    - "yolo11n_C3k2SFS.yaml"
    - "yolo11n_C3k2WConv.yaml"
    - "yolo11n_LDConv.yaml"
    - "yolo11n_OREPA.yaml"

  dataset_yaml: "/NWPU_VHR.yaml"
  epochs: 300
  close_mosaic: 45
  seed: 42
  optimizer: "SGD"
  amp: false
  patience: 0
  pretrained: true
  module_edition: "e0"